const BOOKS = [
  { id:1, title:'Tôi Thấy Hoa Vàng Trên Cỏ Xanh', author:'Nguyễn Nhật Ánh', price:89000, originalPrice:120000, cat:'Văn Học', rating:4.9, reviews:1240, emoji:'<img src="img/book1.png" style="width:100%;height:100%;object-fit:cover" />', badge:'bestseller', description:'Một câu chuyện tuổi thơ đẹp đẽ và đầy cảm xúc về tình anh em, tình bạn và những ký ức không thể quên.' },
  { id:2, title:'Sapiens: Lược Sử Loài Người', author:'Yuval Noah Harari', price:149000, originalPrice:199000, cat:'Khoa Học', rating:4.8, reviews:3420, emoji:'<img src="img/book2.png" style="width:100%;height:100%;object-fit:cover" />', badge:'bestseller', description:'Hành trình 100,000 năm của nhân loại qua lăng kính lịch sử, sinh học và nhân học.' },
  { id:3, title:'Đắc Nhân Tâm', author:'Dale Carnegie', price:79000, originalPrice:95000, cat:'Tâm Lý Học', rating:4.7, reviews:5680, emoji:'<img src="img/book3.png" style="width:100%;height:100%;object-fit:cover" />', badge:'sale', discount:17, description:'Cuốn sách kinh điển giúp bạn hiểu con người và nghệ thuật giao tiếp thuyết phục.' },
  { id:4, title:'Nhà Giả Kim', author:'Paulo Coelho', price:89000, originalPrice:110000, cat:'Văn Học', rating:4.8, reviews:4120, emoji:'<img src="https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'new', description:'Câu chuyện về hành trình tìm kiếm kho báu và khám phá ý nghĩa cuộc sống.' },
  { id:5, title:'Think and Grow Rich', author:'Napoleon Hill', price:119000, originalPrice:150000, cat:'Kinh Tế', rating:4.6, reviews:2890, emoji:'<img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'sale', discount:21, description:'Bí quyết làm giàu từ 13 nguyên tắc tư duy của những người thành công nhất thế giới.' },
  { id:6, title:'Hoàng Tử Bé', author:'Antoine de Saint-Exupéry', price:65000, originalPrice:80000, cat:'Văn Học', rating:4.9, reviews:6780, emoji:'<img src="https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'bestseller', description:'Câu chuyện triết học nhẹ nhàng mà sâu sắc về tình bạn, tình yêu và ý nghĩa cuộc đời.' },
  { id:7, title:'Người Giàu Nhất Thành Babylon', author:'George S. Clason', price:85000, originalPrice:105000, cat:'Kinh Tế', rating:4.7, reviews:2340, emoji:'<img src="https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'new', description:'Những bài học tài chính cá nhân được kể qua các câu chuyện từ thời Babylon cổ đại.' },
  { id:8, title:'7 Thói Quen Hiệu Quả', author:'Stephen R. Covey', price:139000, originalPrice:180000, cat:'Tâm Lý Học', rating:4.8, reviews:4560, emoji:'<img src="https://images.unsplash.com/photo-1589998059171-989d887dda1e?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'bestseller', description:'Bảy nguyên tắc nền tảng giúp bạn trở nên hiệu quả hơn trong cuộc sống và công việc.' },
  { id:9, title:'Cây Cam Ngọt Của Tôi', author:'José Mauro de Vasconcelos', price:99000, originalPrice:120000, cat:'Văn Học', rating:4.9, reviews:8920, emoji:'<img src="https://images.unsplash.com/photo-1474366521946-c3d4b507abf2?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'new', description:'Câu chuyện xúc động về cậu bé Zezé và người bạn đặc biệt — cây cam ngọt trong vườn nhà.' },
  { id:10, title:'Atomic Habits', author:'James Clear', price:155000, originalPrice:199000, cat:'Tâm Lý Học', rating:4.9, reviews:7230, emoji:'<img src="https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600&auto=format&fit=crop" style="width:100%;height:100%;object-fit:cover" />', badge:'bestseller', description:'Hệ thống khoa học để xây dựng thói quen tốt và loại bỏ thói quen xấu.' },
];

const BLOG_POSTS = [
  { id:1, title:'10 Cuốn Sách Thay Đổi Cuộc Đời Bạn Năm 2025', cat:'Top Sách', date:'12/05/2025', emoji:'📚', excerpt:'Những cuốn sách không chỉ là để đọc mà còn để suy nghĩ, để thay đổi và để sống tốt hơn mỗi ngày...', readTime:'8 phút' },
  { id:2, title:'Review: Sapiens - Tại Sao Bạn Bắt Buộc Phải Đọc', cat:'Review Sách', date:'08/05/2025', emoji:'🔬', excerpt:'Yuval Noah Harari đã làm điều không tưởng: biến lịch sử nhân loại thành câu chuyện hấp dẫn nhất bạn từng đọc...', readTime:'6 phút' },
  { id:3, title:'Góc Sách Thiếu Nhi: Top 5 Bộ Sách Cho Bé 6-10 Tuổi', cat:'Thiếu Nhi', date:'03/05/2025', emoji:'⭐', excerpt:'Những bộ sách giúp trẻ yêu đọc sách, phát triển tư duy sáng tạo và xây dựng thói quen học tốt...', readTime:'5 phút' },
];

window.BOOKS = BOOKS;
window.BLOG_POSTS = BLOG_POSTS;
